version: '2'
services:
  sonarqube:
    image: "moonken/sonarqube"
    ports:
     - "9000:9000"
     - "9092:9092"
    environment:
     - SONARQUBE_JDBC_USERNAME=sonarqube
     - SONARQUBE_JDBC_PASSWORD=sonarqube
     - SONARQUBE_JDBC_URL=jdbc:mysql://database:3306/sonar?useUnicode=true&characterEncoding=utf8
    links:
     - database
  database:
    image: "mysql:5.7"
    environment:
     - MYSQL_ROOT_PASSWORD=5ecret
     - MYSQL_USER=sonarqube
     - MYSQL_PASSWORD=sonarqube
     - MYSQL_DATABASE=sonar
  backup:
    image: "schickling/mysql-backup-s3"
    environment:
     - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
     - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
     - S3_BUCKET=17high
     - MYSQLDUMP_DATABASE=sonar
     - MYSQL_HOST=database
     - MYSQL_USER=sonarqube
     - MYSQL_PASSWORD=sonarqube
     - S3_REGION=ap-northeast-1
     - MULTI_FILES=yes
     - SCHEDULE=@daily
    links:
      - database
