version: '2'
services:
  builder:
      image: "tw-wh-devops/dev"
      environment:
       - MYSQL_HOST=database
       - MYSQL_DATABASE=17high
       - MYSQL_USER=17high
       - MYSQL_PASSWORD=17high
       - MYSQL_PORT=3306
       - GRADLE_OPTS="-Dorg.gradle.daemon=false"
      volumes:
       - '.:/app'
      links:
       - database
      command: gradle clean build
  database:
    image: "mysql:5.7"
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=5ecret
     - MYSQL_USER=17high
     - MYSQL_PASSWORD=17high
     - MYSQL_DATABASE=17high
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
  image:
    build: .
    image: twwhdevops/17high_web
#  backup:
#    image: "schickling/mysql-backup-s3"
#    environment:
#     - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
#     - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
#     - S3_BUCKET=17high
#     - MYSQLDUMP_DATABASE=17high
#     - MYSQL_HOST=database
#     - MYSQL_USER=17high
#     - MYSQL_PASSWORD=17high
#     - S3_REGION=ap-northeast-1
#     - MULTI_FILES=yes
#     - SCHEDULE=@daily
#    links:
#      - database
